# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 03:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('spotify_track_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('duration_ms', models.IntegerField()),
                ('explicit', models.BooleanField()),
                ('preview_url', models.CharField(max_length=255)),
                ('href', models.CharField(max_length=255)),
                ('popularity', models.IntegerField()),
                ('uri', models.CharField(max_length=255)),
                ('played', models.BooleanField()),
                ('priority', models.IntegerField()),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party', to='api.Party')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userName', models.CharField(max_length=60)),
                ('spotifyId', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255)),
                ('lastTokenSpotify', models.CharField(max_length=255)),
                ('expireDateTokenSpotify', models.IntegerField()),
                ('account_type', models.CharField(choices=[('f', 'Free'), ('p', 'Premium')], max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='track',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='api.User'),
        ),
        migrations.AddField(
            model_name='party',
            name='current_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_user', to='api.User'),
        ),
        migrations.AddField(
            model_name='party',
            name='members',
            field=models.ManyToManyField(related_name='members', to='api.User'),
        ),
        migrations.AddField(
            model_name='party',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='api.User'),
        ),
    ]
