# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-18 02:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='expireDateTokenSpotify',
            new_name='expire_token_spotify',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='spotifyId',
            new_name='spotify_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lastTokenSpotify',
            new_name='token_spotify',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='userName',
            new_name='username',
        ),
    ]
